//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisuiteEmployeePresentation.LogisuiteEmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://logisuite/employees/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private System.DateTime DateofBirthField;
        
        private decimal AnnualSalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private long PhoneField;
        
        private long SocialSecurityNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateofBirth {
            get {
                return this.DateofBirthField;
            }
            set {
                if ((this.DateofBirthField.Equals(value) != true)) {
                    this.DateofBirthField = value;
                    this.RaisePropertyChanged("DateofBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal AnnualSalary {
            get {
                return this.AnnualSalaryField;
            }
            set {
                if ((this.AnnualSalaryField.Equals(value) != true)) {
                    this.AnnualSalaryField = value;
                    this.RaisePropertyChanged("AnnualSalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((this.PhoneField.Equals(value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long SocialSecurityNumber {
            get {
                return this.SocialSecurityNumberField;
            }
            set {
                if ((this.SocialSecurityNumberField.Equals(value) != true)) {
                    this.SocialSecurityNumberField = value;
                    this.RaisePropertyChanged("SocialSecurityNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://logisuite/employees/", ConfigurationName="LogisuiteEmployeeService.EmployeesServiceSoap")]
    public interface EmployeesServiceSoap {
        
        // CODEGEN: Generating message contract since element name ViewAllResult from namespace http://logisuite/employees/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/ViewAll", ReplyAction="*")]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse ViewAll(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/ViewAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse> ViewAllAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Update", ReplyAction="*")]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse Update(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse> UpdateAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Insert", ReplyAction="*")]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse Insert(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse> InsertAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Delete", ReplyAction="*")]
        int Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
        
        // CODEGEN: Generating message contract since element name SelectResult from namespace http://logisuite/employees/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Select", ReplyAction="*")]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse Select(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse> SelectAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest request);
        
        // CODEGEN: Generating message contract since element name value from namespace http://logisuite/employees/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Search", ReplyAction="*")]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse Search(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://logisuite/employees/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse> SearchAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAll", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequestBody Body;
        
        public ViewAllRequest() {
        }
        
        public ViewAllRequest(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ViewAllRequestBody {
        
        public ViewAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewAllResponse", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponseBody Body;
        
        public ViewAllResponse() {
        }
        
        public ViewAllResponse(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class ViewAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] ViewAllResult;
        
        public ViewAllResponseBody() {
        }
        
        public ViewAllResponseBody(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] ViewAllResult) {
            this.ViewAllResult = ViewAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool result;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(string UpdateResult, bool result) {
            this.UpdateResult = UpdateResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequestBody Body;
        
        public InsertRequest() {
        }
        
        public InsertRequest(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class InsertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value;
        
        public InsertRequestBody() {
        }
        
        public InsertRequestBody(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertResponse", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponseBody Body;
        
        public InsertResponse() {
        }
        
        public InsertResponse(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class InsertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool result;
        
        public InsertResponseBody() {
        }
        
        public InsertResponseBody(string InsertResult, bool result) {
            this.InsertResult = InsertResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Select", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequestBody Body;
        
        public SelectRequest() {
        }
        
        public SelectRequest(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class SelectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SelectRequestBody() {
        }
        
        public SelectRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectResponse", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponseBody Body;
        
        public SelectResponse() {
        }
        
        public SelectResponse(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class SelectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee SelectResult;
        
        public SelectResponseBody() {
        }
        
        public SelectResponseBody(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee SelectResult) {
            this.SelectResult = SelectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://logisuite/employees/", Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://logisuite/employees/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeesServiceSoapChannel : LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeesServiceSoapClient : System.ServiceModel.ClientBase<LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap>, LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap {
        
        public EmployeesServiceSoapClient() {
        }
        
        public EmployeesServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeesServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeesServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.ViewAll(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest request) {
            return base.Channel.ViewAll(request);
        }
        
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] ViewAll() {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequestBody();
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse retVal = ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).ViewAll(inValue);
            return retVal.Body.ViewAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse> LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.ViewAllAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest request) {
            return base.Channel.ViewAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllResponse> ViewAllAsync() {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.ViewAllRequestBody();
            return ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).ViewAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.Update(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value, out bool result) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequestBody();
            inValue.Body.value = value;
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse retVal = ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).Update(inValue);
            result = retVal.Body.result;
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse> LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.UpdateAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateResponse> UpdateAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.UpdateRequestBody();
            inValue.Body.value = value;
            return ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.Insert(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public string Insert(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value, out bool result) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequestBody();
            inValue.Body.value = value;
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse retVal = ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).Insert(inValue);
            result = retVal.Body.result;
            return retVal.Body.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse> LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.InsertAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertResponse> InsertAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee value) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.InsertRequestBody();
            inValue.Body.value = value;
            return ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).InsertAsync(inValue);
        }
        
        public int Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.Select(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest request) {
            return base.Channel.Select(request);
        }
        
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee Select(int id) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequestBody();
            inValue.Body.id = id;
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse retVal = ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).Select(inValue);
            return retVal.Body.SelectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse> LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.SelectAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest request) {
            return base.Channel.SelectAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectResponse> SelectAsync(int id) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SelectRequestBody();
            inValue.Body.id = id;
            return ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).SelectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.Search(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public LogisuiteEmployeePresentation.LogisuiteEmployeeService.Employee[] Search(string value) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequestBody();
            inValue.Body.value = value;
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse retVal = ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse> LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap.SearchAsync(LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchResponse> SearchAsync(string value) {
            LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest inValue = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequest();
            inValue.Body = new LogisuiteEmployeePresentation.LogisuiteEmployeeService.SearchRequestBody();
            inValue.Body.value = value;
            return ((LogisuiteEmployeePresentation.LogisuiteEmployeeService.EmployeesServiceSoap)(this)).SearchAsync(inValue);
        }
    }
}
