//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisuiteEmployeesService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public decimal AnnualSalary { get; set; }
        public string Address { get; set; }
        public long Phone { get; set; }
        public long SocialSecurityNumber { get; set; }
    }
}
